version: '3'

services:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-testapp}
      MYSQL_PASSWORD: ${MYSQLDB_PASSWORD:-appPassword!}
      MYSQL_USER: ${MYSQLDB_USER:-app}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  web:
    build: .
    volumes:
      - .:/app
      - /app/vendor
    depends_on:
      - database